config/routes.rb
Rails.application.routes.draw do
  resources :tirages
  get "grilles" => "grilles#index"
  get "grilles-succes" => "pages#succes"
  get "admin-grilles" => "grilles#gestion"
  get "mes-grilles" => "pages#mesGrilles"
  get "retrait" => "retraits#index"
  get "historique-tirage" => "tirages#histoTir"
  get "historique-tirage/:id" => "tirages#showhistoTir"
  post "admin-grilles" => "grilles#retri"
  post "admin-remun" => "grilles#remun"
  post "admin-code" => "grilles#code"
  post "init" => "pages#init"
  post 'grilles' => 'grilles#create'
  post 'retrait-form' => 'retraits#create'
  get 'admin-retrait' => 'retraits#adminRetrait'
  get "report" => "reports#index"
  devise_for :users
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tirage.rb
class Tirage < ApplicationRecord
   
end

app/controllers/tirages_controller.rb
class TiragesController < ApplicationController
  before_action :set_tirage, only: [:show, :edit, :update, :destroy]

  # GET /tirages
  # GET /tirages.json
  def index
    @tirages = Tirage.all
  end

  # GET /tirages/1
  # GET /tirages/1.json
  def show
  end

  # GET /tirages/new
  def new
    @tirage = Tirage.new
  end

  # GET /tirages/1/edit
  def edit
  end

  # POST /tirages
  # POST /tirages.json
  def create
    @tirage = Tirage.new(tirage_params)

    respond_to do |format|
      if @tirage.save
        format.html { redirect_to @tirage, notice: 'Tirage was successfully created.' }
        format.json { render :show, status: :created, location: @tirage }
      else
        format.html { render :new }
        format.json { render json: @tirage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tirages/1
  # PATCH/PUT /tirages/1.json
  def update
    respond_to do |format|
      if @tirage.update(tirage_params)
        format.html { redirect_to @tirage, notice: 'Tirage was successfully updated.' }
        format.json { render :show, status: :ok, location: @tirage }
      else
        format.html { render :edit }
        format.json { render json: @tirage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tirages/1
  # DELETE /tirages/1.json
  def destroy
    @tirage.destroy
    respond_to do |format|
      format.html { redirect_to tirages_url, notice: 'Tirage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def histoTir
    @histo = Tirage.all.reverse
  end

  def showhistoTir
    @le_tirage = Tirage.find(params[:id])
    
    @perso_grilles= Grille.where("user_id= ?", current_user)
    @by_tirage = @perso_grilles.where("tirage_id= ?", params[:id])
     
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tirage
      @tirage = Tirage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tirage_params
      params.require(:tirage).permit(:t_num1, :t_num2, :t_num3, :t_num4, :t_num5, :t_exp1, :t_exp2, :date_tirage)
    end
end

app/helpers/tirages_helper.rb
module TiragesHelper
end

app/views/tirages/_form.html.erb
<%= form_with(model: tirage, local: true) do |form| %>
  <% if tirage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tirage.errors.count, "error") %> prohibited this tirage from being saved:</h2>

      <ul>
      <% tirage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% select_numbers = p (0..49).to_a.sample(5) %>
  <% select_exp = p (0..12).to_a.sample(2) %>
  
  <div class="field">
    <%= form.label :t_num1 %>
    <%= form.text_field :t_num1 , :value => select_numbers[0]%>
  </div>

  <div class="field">
    <%= form.label :t_num2 %>
    <%= form.text_field :t_num2 , :value => select_numbers[1] %>
  </div>

  <div class="field">
    <%= form.label :t_num3 %>
    <%= form.text_field :t_num3 , :value => select_numbers[2]%>
  </div>

  <div class="field">
    <%= form.label :t_num4 %>
    <%= form.text_field :t_num4 , :value => select_numbers[3]%>
  </div>

  <div class="field">
    <%= form.label :t_num5 %>
    <%= form.text_field :t_num5 , :value => select_numbers[4]%>
  </div>

  <div class="field">
    <%= form.label :t_exp1 %>
    <%= form.text_field :t_exp1 , :value => select_exp[0] %>
  </div>

  <div class="field">
    <%= form.label :t_exp2 %>
    <%= form.text_field :t_exp2 , :value => select_exp[1] %>
  </div>

  <div class="field">
    <%= form.label :date_tirage %>
    <%= form.date_select :date_tirage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tirages/edit.html.erb
<h1>Editing Tirage</h1>

<%= render 'form', tirage: @tirage %>

<%= link_to 'Show', @tirage %> |
<%= link_to 'Back', tirages_path %>

app/views/tirages/histoTir.html.erb
<% content_for :css do
    stylesheet_link_tag 'mes-grilles'
end %>

<div id="back">
           <div class="container">
                  <h1>Les tirages</h1>
    
    
        
            <% @histo.each do |tirage| %>
                <section>
                <center>
                <button class="num"><%= tirage.t_num1 %></button>
                <button class="num"><%= tirage.t_num2 %></button>
                <button class="num"><%= tirage.t_num3 %></button>
                <button class="num"><%= tirage.t_num4 %></button>
                <button class="num"><%= tirage.t_num5 %></button>
                
                <button class="exp"><%= tirage.t_exp1 %></button>
                <button class="exp"><%= tirage.t_exp2 %></button>
                <a class="info" href="/historique-tirage/<%= tirage.id %>"><i class="material-icons md-64"> poll</i></a>
                <div class="separate"></div>
                </center>
            </section>
            <% end %>
        
</div>
<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>

app/views/tirages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tirages</h1>

<table class="blueTable">
  <thead>
    <tr>
      <th>T num1</th>
      <th>T num2</th>
      <th>T num3</th>
      <th>T num4</th>
      <th>T num5</th>
      <th>T exp1</th>
      <th>T exp2</th>
      <th>Date tirage</th>
      <th>ID</th>
      <th>Nb grilles jouer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tirages.each do |tirage| %>
      <tr>
        <td><%= tirage.t_num1 %></td>
        <td><%= tirage.t_num2 %></td>
        <td><%= tirage.t_num3 %></td>
        <td><%= tirage.t_num4 %></td>
        <td><%= tirage.t_num5 %></td>
        <td><%= tirage.t_exp1 %></td>
        <td><%= tirage.t_exp2 %></td>
        <td><%= tirage.date_tirage %></td>
        <td><%= tirage.id %></td>
        <td><%= tirage.nb_jouer %></td>
        <td><%= link_to 'Show', tirage %></td>
        <td><%= link_to 'Edit', edit_tirage_path(tirage) %></td>
        <td><%= link_to 'Destroy', tirage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tirage', new_tirage_path %>

app/views/tirages/new.html.erb
<h1>New Tirage</h1>

<%= render 'form', tirage: @tirage %>

<%= link_to 'Back', tirages_path %>

app/views/tirages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>T num1:</strong>
  <%= @tirage.t_num1 %>
</p>

<p>
  <strong>T num2:</strong>
  <%= @tirage.t_num2 %>
</p>

<p>
  <strong>T num3:</strong>
  <%= @tirage.t_num3 %>
</p>

<p>
  <strong>T num4:</strong>
  <%= @tirage.t_num4 %>
</p>

<p>
  <strong>T num5:</strong>
  <%= @tirage.t_num5 %>
</p>

<p>
  <strong>T exp1:</strong>
  <%= @tirage.t_exp1 %>
</p>

<p>
  <strong>T exp2:</strong>
  <%= @tirage.t_exp2 %>
</p>

<p>
  <strong>Date tirage:</strong>
  <%= @tirage.date_tirage %>
</p>

<%= link_to 'Edit', edit_tirage_path(@tirage) %> |
<%= link_to 'Back', tirages_path %>

app/views/tirages/showhistoTir.html.erb
<% content_for :css do
    stylesheet_link_tag 'mes-grilles'
end %>

<div id="back">
           <div class="container">
                  <h1>Informations</h1>
                   <div class="separate"></div>
                <h2> Les bons numéros étaient</h2>
            <section>
                <center>
                <button class="num"><%= @le_tirage.t_num1 %></button>
                <button class="num"><%= @le_tirage.t_num2 %></button>
                <button class="num"><%= @le_tirage.t_num3 %></button>
                <button class="num"><%= @le_tirage.t_num4 %></button>
                <button class="num"><%= @le_tirage.t_num5 %></button>
                <button class="exp"><%= @le_tirage.t_exp1 %></button>
                <button class="exp"><%= @le_tirage.t_exp2 %></button>
                </center>
            </section>
            
           <h2>Vous avez Joué :</h2> 
           
           <table>
              <% gain = 0.00 %>
            <% @by_tirage.each do |one_grilles_per_user| %>
            <center>
            <section class="ligne">
            <button class="num" ><%= one_grilles_per_user.num1 %></button>
            <button class="num" ><%= one_grilles_per_user.num2 %></button>
            <button class="num" ><%= one_grilles_per_user.num3 %></button>
            <button class="num" ><%= one_grilles_per_user.num4 %></button>
            <button class="num" ><%= one_grilles_per_user.num5 %></button>
            <button class="exp" ><%= one_grilles_per_user.exp1 %></button>
            <button class="exp" ><%= one_grilles_per_user.exp2 %></button>
            </section>
            </center>
            <% if one_grilles_per_user.gain != nil %>
            <% gain += one_grilles_per_user.gain%>
            <% end %>
            <% end %>
            </table>
           
              <h2>Vous avez Gagné :</h2>
              
              <h1><%=  gain %> €</h1>
</div>
<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>